import type ITelemetryData from "@/objects/telemetry-data.interface";
import { faker } from "@faker-js/faker";

export function generateFakeTelemetryData(): ITelemetryData {
  return {
    PacketTitle: faker.lorem.words(2),
    AuxBms: {
      AllowCharge: faker.datatype.boolean(0.01),
      AllowDischarge: faker.datatype.boolean(0.01),
      AuxBmsAlive: faker.datatype.boolean(0.01),
      AuxVoltage: faker.number.int({ min: 0, max: 100 }),
      ChargeContactorError: faker.datatype.boolean(0.01),
      ChargeNotClosedDueToHighCurrent: faker.datatype.boolean(0.01),
      ChargeOpenButShouldBeClosed: faker.datatype.boolean(0.01),
      ChargeShouldTrip: faker.datatype.boolean(0.01),
      ChargeTripDueToHighCellVoltage: faker.datatype.boolean(0.01),
      ChargeTripDueToHighTemperatureAndCurrent: faker.datatype.boolean(0.01),
      ChargeTripDueToPackCurrent: faker.datatype.boolean(0.01),
      CommonContactorError: faker.datatype.boolean(0.01),
      DischargeContactorError: faker.datatype.boolean(0.01),
      DischargeNotClosedDueToHighCurrent: faker.datatype.boolean(0.01),
      DischargeOpenButShouldBeClosed: faker.datatype.boolean(0.01),
      DischargeShouldTrip: faker.datatype.boolean(0.01),
      DischargeTripDueToHighTemperatureAndCurrent: faker.datatype.boolean(0.01),
      DischargeTripDueToLowCellVoltage: faker.datatype.boolean(0.01),
      DischargeTripDueToPackCurrent: faker.datatype.boolean(0.01),
      HighVoltageEnableState: faker.datatype.boolean(0.01),
      OrionCANReceivedRecently: faker.datatype.boolean(0.01),
      PrechargeState: faker.lorem.words(2),
      ProtectionTrip: faker.datatype.boolean(0.01),
      StrobeBmsLight: faker.datatype.boolean(0.01),
      TripDueToOrionMessageTimeout: faker.datatype.boolean(0.01),
    },
    Battery: {
      Alive: faker.datatype.boolean(0.01),
      BMSRelayStatusFlags: {
        DischargeRelayEnabled: faker.datatype.boolean(0.01),
        ChargeRelayEnabled: faker.datatype.boolean(0.01),
        ChargerSafetyEnabled: faker.datatype.boolean(0.01),
        MalfunctionIndicatorActive: faker.datatype.boolean(0.01),
        MultiPurposeInputSignalStatus: faker.datatype.boolean(0.01),
        AlwaysOnSignalStatus: faker.datatype.boolean(0.01),
        IsReadySignalStatus: faker.datatype.boolean(0.01),
        IsChargingSignalStatus: faker.datatype.boolean(0.01),
      },
      PopulatedCells: faker.number.int({ min: 0, max: 100 }),
      "12vInputVoltage": faker.number.int({ min: 0, max: 100 }),
      FanVoltage: faker.number.int({ min: 0, max: 100 }),
      PackCurrent: faker.number.int({ min: 0, max: 100 }),
      PackVoltage: faker.number.int({ min: 0, max: 100 }),
      PackStateOfCharge: faker.number.int({ min: 0, max: 100 }),
      PackAmphours: faker.number.int({ min: 0, max: 100 }),
      PackDepthOfDischarge: faker.number.int({ min: 0, max: 100 }),
      HighTemperature: faker.number.int({ min: 0, max: 100 }),
      HighThermistorId: faker.number.int({ min: 0, max: 100 }),
      LowTemperature: faker.number.int({ min: 0, max: 100 }),
      LowThermistorId: faker.number.int({ min: 0, max: 100 }),
      AverageTemperature: faker.number.int({ min: 0, max: 100 }),
      InternalTemperature: faker.number.int({ min: 0, max: 100 }),
      FanSpeed: faker.number.int({ min: 0, max: 100 }),
      RequestedFanSpeed: faker.number.int({ min: 0, max: 100 }),
      LowCellVoltage: faker.number.int({ min: 0, max: 100 }),
      LowCellVoltageId: faker.number.int({ min: 0, max: 100 }),
      HighCellVoltage: faker.number.int({ min: 0, max: 100 }),
      HighCellVoltageId: faker.number.int({ min: 0, max: 100 }),
      AverageCellVoltage: faker.number.int({ min: 0, max: 100 }),
    },
    BatteryFaults: {
      ErrorFlags: {
        InternalCommunicationFault: faker.datatype.boolean(0.01),
        InternalConversionFault: faker.datatype.boolean(0.01),
        WeakCellFault: faker.datatype.boolean(0.01),
        LowCellVoltageFault: faker.datatype.boolean(0.01),
        OpenWiringFault: faker.datatype.boolean(0.01),
        CurrentSensorFault: faker.datatype.boolean(0.01),
        PackVoltageSensorFault: faker.datatype.boolean(0.01),
        WeakPackFault: faker.datatype.boolean(0.01),
        VoltageRedundancyFault: faker.datatype.boolean(0.01),
        FanMonitorFault: faker.datatype.boolean(0.01),
        ThermistorFault: faker.datatype.boolean(0.01),
        CANBUSCommunicationsFault: faker.datatype.boolean(0.01),
        AlwaysOnSupplyFault: faker.datatype.boolean(0.01),
        HighVoltageIsolationFault: faker.datatype.boolean(0.01),
        "12vPowerSupplyFault": faker.datatype.boolean(0.01),
        ChargeLimitEnforcementFault: faker.datatype.boolean(0.01),
        DischargeLimitEnforcementFault: faker.datatype.boolean(0.01),
        ChargerSafetyRelayFault: faker.datatype.boolean(0.01),
        InternalMemoryFault: faker.datatype.boolean(0.01),
        InternalThermistorsFault: faker.datatype.boolean(0.01),
        InternalLogicFault: faker.datatype.boolean(0.01),
      },
      LimitFlags: {
        DclReducedDueToLowSoc: faker.datatype.boolean(0.01),
        DclReducedDueToHighCellResistance: faker.datatype.boolean(0.01),
        DclReducedDueToTemperature: faker.datatype.boolean(0.01),
        DclReducedDueToLowCellVoltage: faker.datatype.boolean(0.01),
        DclReducedDueToLowPackVoltage: faker.datatype.boolean(0.01),
        DclandCclReducedDueToVoltageFailsafe: faker.datatype.boolean(0.01),
        DclandCclReducedDueToCommunicationFailsafe:
          faker.datatype.boolean(0.01),
        CclReducedDueToHighSoc: faker.datatype.boolean(0.01),
        CclReducedDueToHighCellResistance: faker.datatype.boolean(0.01),
        CclReducedDueToTemperature: faker.datatype.boolean(0.01),
        CclReducedDueToHighCellVoltage: faker.datatype.boolean(0.01),
        CclReducedDueToHighPackVoltage: faker.datatype.boolean(0.01),
        CclReducedDueToChargerLatch: faker.datatype.boolean(0.01),
        CclReducedDueToAlternateCurrentLimit: faker.datatype.boolean(0.01),
      },
    },
    Ccs: {
      CcsAlive: faker.datatype.boolean(0.01),
    },
    DriverControls: {
      Alive: faker.datatype.boolean(0.01),
      HeadlightsOff: faker.datatype.boolean(0.01),
      HeadlightsLow: faker.datatype.boolean(0.01),
      HeadlightsHigh: faker.datatype.boolean(0.01),
      SignalRight: faker.datatype.boolean(0.01),
      SignalLeft: faker.datatype.boolean(0.01),
      Hazard: faker.datatype.boolean(0.01),
      Interior: faker.datatype.boolean(0.01),
      Aux: faker.datatype.boolean(0.01),
      VolumeUp: faker.datatype.boolean(0.01),
      VolumeDown: faker.datatype.boolean(0.01),
      NextSong: faker.datatype.boolean(0.01),
      PrevSong: faker.datatype.boolean(0.01),
      Acceleration: faker.number.int({ min: 0, max: 100 }),
      RegenBraking: faker.number.int({ min: 0, max: 100 }),
      Brakes: faker.datatype.boolean(0.01),
      Forward: faker.datatype.boolean(0.01),
      Reverse: faker.datatype.boolean(0.01),
      PushToTalk: faker.datatype.boolean(0.01),
      Horn: faker.datatype.boolean(0.01),
      Reset: faker.datatype.boolean(0.01),
      Lap: faker.datatype.boolean(0.01),
    },
    KeyMotor: [
      {
        Alive: faker.datatype.boolean(0.01),
        BusCurrent: faker.number.int({ min: 0, max: 100 }),
        BusVoltage: faker.number.int({ min: 0, max: 100 }),
        SetCurrent: faker.number.int({ min: 0, max: 100 }),
        SetVelocity: faker.number.int({ min: 0, max: 100 }),
        VehicleVelocity: faker.number.int({ min: 0, max: 100 }),
      },
      {
        Alive: faker.datatype.boolean(0.01),
        BusCurrent: faker.number.int({ min: 0, max: 100 }),
        BusVoltage: faker.number.int({ min: 0, max: 100 }),
        SetCurrent: faker.number.int({ min: 0, max: 100 }),
        SetVelocity: faker.number.int({ min: 0, max: 100 }),
        VehicleVelocity: faker.number.int({ min: 0, max: 100 }),
      },
    ],
    MotorFaults: [
      {
        ErrorFlags: {
          MotorOverSpeed: faker.datatype.boolean(0.01),
          SoftwareOverCurrent: faker.datatype.boolean(0.01),
          DcBusOverVoltage: faker.datatype.boolean(0.01),
          BadMotorPositionHallSequence: faker.datatype.boolean(0.01),
          WatchdogCausedLastReset: faker.datatype.boolean(0.01),
          ConfigReadError: faker.datatype.boolean(0.01),
          Wail15VUnderVoltageLockOut: faker.datatype.boolean(0.01),
          DesaturationFault: faker.datatype.boolean(0.01),
        },
        LimitFlags: {
          OutputVoltagePwm: faker.datatype.boolean(0.01),
          MotorCurrent: faker.datatype.boolean(0.01),
          Velocity: faker.datatype.boolean(0.01),
          BusCurrent: false,
          BusVoltageUpper: faker.datatype.boolean(0.01),
          BusVoltageLower: faker.datatype.boolean(0.01),
          IpmOrMotorTemperature: true,
        },
        RxErrorCount: faker.number.int({ min: 0, max: 100 }),
        TxErrorCount: faker.number.int({ min: 0, max: 100 }),
      },
      {
        ErrorFlags: {
          MotorOverSpeed: faker.datatype.boolean(0.01),
          SoftwareOverCurrent: faker.datatype.boolean(0.01),
          DcBusOverVoltage: faker.datatype.boolean(0.01),
          BadMotorPositionHallSequence: faker.datatype.boolean(0.01),
          WatchdogCausedLastReset: faker.datatype.boolean(0.01),
          ConfigReadError: faker.datatype.boolean(0.01),
          Wail15VUnderVoltageLockOut: faker.datatype.boolean(0.01),
          DesaturationFault: faker.datatype.boolean(0.01),
        },
        LimitFlags: {
          OutputVoltagePwm: faker.datatype.boolean(0.01),
          MotorCurrent: faker.datatype.boolean(0.01),
          Velocity: faker.datatype.boolean(0.01),
          BusCurrent: false,
          BusVoltageUpper: faker.datatype.boolean(0.01),
          BusVoltageLower: faker.datatype.boolean(0.01),
          IpmOrMotorTemperature: true,
        },
        RxErrorCount: faker.number.int({ min: 0, max: 100 }),
        TxErrorCount: faker.number.int({ min: 0, max: 100 }),
      },
    ],
    MotorDetails: [
      {
        BackEmf: faker.number.int({ min: 0, max: 100 }),
        DcBusAmpHours: faker.number.int({ min: 0, max: 100 }),
        DspBoardTemp: faker.number.int({ min: 0, max: 100 }),
        HeatSinkTemp: faker.number.int({ min: 0, max: 100 }),
        MotorCurrentImaginary: faker.number.int({ min: 0, max: 100 }),
        MotorCurrentReal: faker.number.int({ min: 0, max: 100 }),
        MotorTemp: faker.number.int({ min: 0, max: 100 }),
        MotorVoltageImaginary: faker.number.int({ min: 0, max: 100 }),
        MotorVoltageReal: faker.number.int({ min: 0, max: 100 }),
        Odometer: faker.number.int({ min: 0, max: 100 }),
        SlipSpeed: faker.number.int({ min: 0, max: 100 }),
        PhaseBCurrent: faker.number.int({ min: 0, max: 100 }),
        PhaseCCurrent: faker.number.int({ min: 0, max: 100 }),
        VoltageRail15VSupply: faker.number.int({ min: 0, max: 100 }),
        VoltageRail1VSupply: faker.number.int({ min: 0, max: 100 }),
        VoltageRail3VSupply: faker.number.int({ min: 0, max: 100 }),
      },
      {
        BackEmf: faker.number.int({ min: 0, max: 100 }),
        DcBusAmpHours: faker.number.int({ min: 0, max: 100 }),
        DspBoardTemp: faker.number.int({ min: 0, max: 100 }),
        HeatSinkTemp: faker.number.int({ min: 0, max: 100 }),
        MotorCurrentImaginary: faker.number.int({ min: 0, max: 100 }),
        MotorCurrentReal: faker.number.int({ min: 0, max: 100 }),
        MotorTemp: faker.number.int({ min: 0, max: 100 }),
        MotorVoltageImaginary: faker.number.int({ min: 0, max: 100 }),
        MotorVoltageReal: faker.number.int({ min: 0, max: 100 }),
        Odometer: faker.number.int({ min: 0, max: 100 }),
        SlipSpeed: faker.number.int({ min: 0, max: 100 }),
        PhaseBCurrent: faker.number.int({ min: 0, max: 100 }),
        PhaseCCurrent: faker.number.int({ min: 0, max: 100 }),
        VoltageRail15VSupply: faker.number.int({ min: 0, max: 100 }),
        VoltageRail1VSupply: faker.number.int({ min: 0, max: 100 }),
        VoltageRail3VSupply: faker.number.int({ min: 0, max: 100 }),
      },
    ],
    Lights: {
      LowBeams: faker.datatype.boolean(0.01),
      HighBeams: faker.datatype.boolean(0.01),
      Brakes: faker.datatype.boolean(0.01),
      LeftSignal: faker.datatype.boolean(0.01),
      RightSignal: faker.datatype.boolean(0.01),
      BmsStrobeLight: faker.datatype.boolean(0.01),
      Alive: faker.datatype.boolean(0.01),
    },
    MPPT: [
      {
        Alive: faker.datatype.boolean(0.01),
        ArrayCurrent: faker.number.int({ min: 0, max: 100 }),
        ArrayVoltage: faker.number.int({ min: 0, max: 100 }),
        BatteryVoltage: faker.number.int({ min: 0, max: 100 }),
        Temperature: faker.number.int({ min: 0, max: 100 }),
      },
      {
        Alive: faker.datatype.boolean(0.01),
        ArrayCurrent: faker.number.int({ min: 0, max: 100 }),
        ArrayVoltage: faker.number.int({ min: 0, max: 100 }),
        BatteryVoltage: faker.number.int({ min: 0, max: 100 }),
        Temperature: faker.number.int({ min: 0, max: 100 }),
      },
      {
        Alive: faker.datatype.boolean(0.01),
        ArrayCurrent: faker.number.int({ min: 0, max: 100 }),
        ArrayVoltage: faker.number.int({ min: 0, max: 100 }),
        BatteryVoltage: faker.number.int({ min: 0, max: 100 }),
        Temperature: faker.number.int({ min: 0, max: 100 }),
      },
      {
        Alive: faker.datatype.boolean(0.01),
        ArrayCurrent: faker.number.int({ min: 0, max: 100 }),
        ArrayVoltage: faker.number.int({ min: 0, max: 100 }),
        BatteryVoltage: faker.number.int({ min: 0, max: 100 }),
        Temperature: faker.number.int({ min: 0, max: 100 }),
      },
    ],
    TimeStamp: faker.date.soon().valueOf(),
  };
}
