env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: [./web-app/tsconfig.json, ./server/tsconfig.json]
plugins:
  - react
ignorePatterns: [
  "index.ts",
  "configExample.ts",
]
rules: {
  "@typescript-eslint/explicit-function-return-type": "off",
  "@typescript-eslint/return-await": "off",
  "@typescript-eslint/restrict-template-expressions": "off",
}
