import type { telemetry_packet } from "@prisma/client";

import type { ITelemetryData } from "@shared/helios-types";

/**
 * Utility class for transforming telemetry data between nested objects and flat database rows.
 *
 * Handles bidirectional conversion:
 * - flatten: ITelemetryData (nested) → TelemetryPacket (flat database row)
 * - inflate: TelemetryPacket (flat database row) → ITelemetryData (nested)
 */
export class TelemetryTransformer {
  /**
   * Converts a nested ITelemetryData object into a flat database row.
   *
   * @param packet - Nested telemetry data from MQTT
   * @returns Flat object ready for database insertion
   */
  static flatten(packet: ITelemetryData): Partial<telemetry_packet> {
    const timestamp = new Date(packet.TimeStamp * 1000);
    const Rfid = packet.Pi.Rfid;

    return {
      // Metadata
      RaceName: packet.Title,
      rfid: Rfid,
      // Primary keys
      timestamp: timestamp,
      Title: packet.Title,

      // B3 data
      ...packet.B3,

      // Battery data
      ...packet.Battery,

      // Battery Faults (flatten Errors and Warnings)
      ...packet.BatteryFaults.Errors,
      ...packet.BatteryFaults.Warnings,

      // Contactor data
      ...packet.Contactor,

      // KeyMotor data
      ...packet.KeyMotor,

      // MBMS data
      ...packet.MBMS,

      // MPPT data
      ...packet.MPPT,

      // Motor 0 data (prefix all fields with Motor0)
      Motor0ActiveMotor: packet.MotorDetails0.ActiveMotor,
      Motor0BemfD: packet.MotorDetails0.BEMF_D,
      Motor0BemfQ: packet.MotorDetails0.BEMF_Q,
      Motor0BusCurrent: packet.MotorDetails0.BusCurrent,
      Motor0BusVoltage: packet.MotorDetails0.BusVoltage,
      Motor0DcBusAh: packet.MotorDetails0.DC_Bus_Ah,
      Motor0DspBoardTemperature: packet.MotorDetails0.DspBoardTemperature,
      Motor0ErrorFlags: packet.MotorDetails0.ErrorFlags,
      Motor0HeatsinkTemperature: packet.MotorDetails0.HeatsinkTemperature,
      Motor0Id: packet.MotorDetails0.Id,
      Motor0Iq: packet.MotorDetails0.Iq,
      Motor0LimitFlags: packet.MotorDetails0.LimitFlags,
      Motor0MotorTemperature: packet.MotorDetails0.MotorTemperature,
      Motor0MotorVelocity: packet.MotorDetails0.MotorVelocity,
      Motor0Odometer: packet.MotorDetails0.Odometer,
      Motor0PhaseCurrentB: packet.MotorDetails0.PhaseCurrentB,
      Motor0PhaseCurrentC: packet.MotorDetails0.PhaseCurrentC,
      Motor0RxErrorCount: packet.MotorDetails0.RxErrorCount,
      Motor0SerialNumber: packet.MotorDetails0.SerialNumber,
      Motor0SlipSpeed: packet.MotorDetails0.SlipSpeed,
      Motor0Supply15v: packet.MotorDetails0.Supply15V,
      Motor0Supply1v9: packet.MotorDetails0.Supply1V9,
      Motor0Supply3v3: packet.MotorDetails0.Supply3V3,
      Motor0TritiumId: packet.MotorDetails0.TritiumId,
      Motor0TxErrorCount: packet.MotorDetails0.TxErrorCount,
      Motor0Vd: packet.MotorDetails0.Vd,
      Motor0VehicleVelocity: packet.MotorDetails0.VehicleVelocity,
      Motor0Vq: packet.MotorDetails0.Vq,

      // Motor 1 data (prefix all fields with Motor1)
      Motor1ActiveMotor: packet.MotorDetails1.ActiveMotor,
      Motor1BemfD: packet.MotorDetails1.BEMF_D,
      Motor1BemfQ: packet.MotorDetails1.BEMF_Q,
      Motor1BusCurrent: packet.MotorDetails1.BusCurrent,
      Motor1BusVoltage: packet.MotorDetails1.BusVoltage,
      Motor1DcBusAh: packet.MotorDetails1.DC_Bus_Ah,
      Motor1DspBoardTemperature: packet.MotorDetails1.DspBoardTemperature,
      Motor1ErrorFlags: packet.MotorDetails1.ErrorFlags,
      Motor1HeatsinkTemperature: packet.MotorDetails1.HeatsinkTemperature,
      Motor1Id: packet.MotorDetails1.Id,
      Motor1Iq: packet.MotorDetails1.Iq,
      Motor1LimitFlags: packet.MotorDetails1.LimitFlags,
      Motor1MotorTemperature: packet.MotorDetails1.MotorTemperature,
      Motor1MotorVelocity: packet.MotorDetails1.MotorVelocity,
      Motor1Odometer: packet.MotorDetails1.Odometer,
      Motor1PhaseCurrentB: packet.MotorDetails1.PhaseCurrentB,
      Motor1PhaseCurrentC: packet.MotorDetails1.PhaseCurrentC,
      Motor1RxErrorCount: packet.MotorDetails1.RxErrorCount,
      Motor1SerialNumber: packet.MotorDetails1.SerialNumber,
      Motor1SlipSpeed: packet.MotorDetails1.SlipSpeed,
      Motor1Supply15v: packet.MotorDetails1.Supply15V,
      Motor1Supply1v9: packet.MotorDetails1.Supply1V9,
      Motor1Supply3v3: packet.MotorDetails1.Supply3V3,
      Motor1TritiumId: packet.MotorDetails1.TritiumId,
      Motor1TxErrorCount: packet.MotorDetails1.TxErrorCount,
      Motor1Vd: packet.MotorDetails1.Vd,
      Motor1VehicleVelocity: packet.MotorDetails1.VehicleVelocity,
      Motor1Vq: packet.MotorDetails1.Vq,

      // ProximitySensors data
      ...packet.ProximitySensors,

      // Telemetry data (GPS + MPU)
      ...packet.Telemetry,
    };
  }

  /**
   * Converts a flat database row back into a nested ITelemetryData object.
   *
   * @param packet - Flat database row
   * @returns Nested telemetry data structure
   */
  static inflate(packet: telemetry_packet): ITelemetryData {
    return {
      B3: {
        Acceleration: packet.Acceleration ?? 0,
        B3Heartbeat: packet.B3Heartbeat ?? false,
        BrakeLightSignalStatus: packet.BrakeLightSignalStatus ?? false,
        BrakeSwitchDigital: packet.BrakeSwitchDigital ?? false,
        DaytimeRunningLightSignalStatus: packet.DaytimeRunningLightSignalStatus ?? false,
        ForwardDigital: packet.ForwardDigital ?? false,
        HandbrakeSwitchDigital: packet.HandbrakeSwitchDigital ?? false,
        HazardLightsInput: packet.HazardLightsInput ?? false,
        HeadlightsSwitchInput: packet.HeadlightsSwitchInput ?? false,
        HeadlightSignalStatus: packet.HeadlightSignalStatus ?? false,
        HornSignalStatus: packet.HornSignalStatus ?? false,
        HornSwitchDigital: packet.HornSwitchDigital ?? false,
        LapDigital: packet.LapDigital ?? false,
        LeftSignalInput: packet.LeftSignalInput ?? false,
        LeftSignalStatus: packet.LeftSignalStatus ?? false,
        MotorResetDigital: packet.MotorResetDigital ?? false,
        NeutralDigital: packet.NeutralDigital ?? false,
        RaceModeDigital: packet.RaceModeDigital ?? false,
        RegenBraking: packet.RegenBraking ?? 0,
        ReverseDigital: packet.ReverseDigital ?? false,
        RightSignalInput: packet.RightSignalInput ?? false,
        RightSignalStatus: packet.RightSignalStatus ?? false,
      },
      Battery: {
        AlwaysOnSignalStatus: packet.AlwaysOnSignalStatus ?? false,
        AverageCellVoltage: packet.AverageCellVoltage ?? 0,
        AverageTemperature: packet.AverageTemperature ?? 0,
        BmuAlive: packet.BmuAlive ?? 0,
        ChargeRelayEnabled: packet.ChargeRelayEnabled ?? false,
        ChargerSafetyEnabled: packet.ChargerSafetyEnabled ?? false,
        DischargeRelayEnabled: packet.DischargeRelayEnabled ?? false,
        FanSpeed: packet.FanSpeed ?? 0,
        FanVoltage: packet.FanVoltage ?? 0,
        HighCellVoltage: packet.HighCellVoltage ?? 0,
        HighCellVoltageId: packet.HighCellVoltageId ?? 0,
        HighTemperature: packet.HighTemperature ?? 0,
        HighThermistorId: packet.HighThermistorId ?? 0,
        Input12V: packet.Input12V ?? 0,
        InternalTemperature: packet.InternalTemperature ?? 0,
        IsChargingSignalStatus: packet.IsChargingSignalStatus ?? false,
        IsReadySignalStatus: packet.IsReadySignalStatus ?? false,
        LowCellVoltage: packet.LowCellVoltage ?? 0,
        LowCellVoltageId: packet.LowCellVoltageId ?? 0,
        LowTemperature: packet.LowTemperature ?? 0,
        LowThermistorId: packet.LowThermistorId ?? 0,
        MalfunctionIndicatorActive: packet.MalfunctionIndicatorActive ?? false,
        MaximumCellVoltage: packet.MaximumCellVoltage ?? 0,
        MaximumPackVoltage: packet.MaximumPackVoltage ?? 0,
        MinimumCellVoltage: packet.MinimumCellVoltage ?? 0,
        MinimumPackVoltage: packet.MinimumPackVoltage ?? 0,
        MultiPurposeInputSignalStatus: packet.MultiPurposeInputSignalStatus ?? false,
        PackAmphours: packet.PackAmphours ?? 0,
        PackCurrent: packet.PackCurrent ?? 0,
        PackDepthOfDischarge: packet.PackDepthOfDischarge ?? 0,
        PackStateOfCharge: packet.PackStateOfCharge ?? 0,
        PackVoltage: packet.PackVoltage ?? 0,
        PopulatedCells: packet.PopulatedCells ?? 0,
        RequestedFanSpeed: packet.RequestedFanSpeed ?? 0,
      },
      BatteryFaults: {
        Errors: {
          AlwaysOnSupplyFault: packet.AlwaysOnSupplyFault ?? false,
          CanbusCommunicationFault: packet.CanbusCommunicationFault ?? false,
          ChargeLimitEnforcementFault: packet.ChargeLimitEnforcementFault ?? false,
          ChargerSafetyRelayFault: packet.ChargerSafetyRelayFault ?? false,
          CurrentSensorFault: packet.CurrentSensorFault ?? false,
          DischargeLimitEnforcementFault: packet.DischargeLimitEnforcementFault ?? false,
          FanMonitorFault: packet.FanMonitorFault ?? false,
          HighVoltageIsolationFault: packet.HighVoltageIsolationFault ?? false,
          InternalCommunicationFault: packet.InternalCommunicationFault ?? false,
          InternalConversionFault: packet.InternalConversionFault ?? false,
          InternalLogicFault: packet.InternalLogicFault ?? false,
          InternalMemoryFault: packet.InternalMemoryFault ?? false,
          InternalThermistorFault: packet.InternalThermistorFault ?? false,
          LowCellVoltageFault: packet.LowCellVoltageFault ?? false,
          OpenWiringFault: packet.OpenWiringFault ?? false,
          PackVoltageSensorFault: packet.PackVoltageSensorFault ?? false,
          PowerSupply12VFault: packet.PowerSupply12VFault ?? false,
          ThermistorFault: packet.ThermistorFault ?? false,
          VoltageRedundancyFault: packet.VoltageRedundancyFault ?? false,
          WeakCellFault: packet.WeakCellFault ?? false,
          WeakPackFault: packet.WeakPackFault ?? false,
        },
        Warnings: {
          CclReducedDueToAlternateCurrentLimit:
            packet.CclReducedDueToAlternateCurrentLimit ?? false,
          CclReducedDueToChargerLatch:
            packet.CclReducedDueToChargerLatch ?? false,
          CclReducedDueToHighCellResistance:
            packet.CclReducedDueToHighCellResistance ?? false,
          CclReducedDueToHighCellVoltage:
            packet.CclReducedDueToHighCellVoltage ?? false,
          CclReducedDueToHighPackVoltage:
            packet.CclReducedDueToHighPackVoltage ?? false,
          CclReducedDueToHighSoc: packet.CclReducedDueToHighSoc ?? false,
          CclReducedDueToTemperature:
            packet.CclReducedDueToTemperature ?? false,
          DclAndCclReducedDueToCommunicationFailsafe:
            packet.DclAndCclReducedDueToCommunicationFailsafe ?? false,
          DclAndCclReducedDueToVoltageFailsafe:
            packet.DclAndCclReducedDueToVoltageFailsafe ?? false,
          DclReducedDueToHighCellResistance:
            packet.DclReducedDueToHighCellResistance ?? false,
          DclReducedDueToLowCellVoltage:
            packet.DclReducedDueToLowCellVoltage ?? false,
          DclReducedDueToLowPackVoltage:
            packet.DclReducedDueToLowPackVoltage ?? false,
          DclReducedDueToLowSoc: packet.DclReducedDueToLowSoc ?? false,
          DclReducedDueToTemperature:
            packet.DclReducedDueToTemperature ?? false,
        },
      },
      Contactor: {
        ArrayBPSError: packet.ArrayBPSError ?? false,
        ArrayChargeCurrent: packet.ArrayChargeCurrent ?? 0,
        ArrayContactorClosed: packet.ArrayContactorClosed ?? false,
        ArrayContactorClosing: packet.ArrayContactorClosing ?? false,
        ArrayContactorError: packet.ArrayContactorError ?? false,
        ArrayHeartbeat: packet.ArrayHeartbeat ?? false,
        ArrayLineCurrent: packet.ArrayLineCurrent ?? 0,
        ArrayPrechargerClosed: packet.ArrayPrechargerClosed ?? false,
        ArrayPrechargerClosing: packet.ArrayPrechargerClosing ?? false,
        ArrayPrechargerError: packet.ArrayPrechargerError ?? false,
        ChargeBPSError: packet.ChargeBPSError ?? false,
        ChargeChargeCurrent: packet.ChargeChargeCurrent ?? 0,
        ChargeContactorClosed: packet.ChargeContactorClosed ?? false,
        ChargeContactorClosing: packet.ChargeContactorClosing ?? false,
        ChargeContactorError: packet.ChargeContactorError ?? false,
        ChargeHeartbeat: packet.ChargeHeartbeat ?? false,
        ChargeLineCurrent: packet.ChargeLineCurrent ?? 0,
        ChargePrechargerClosed: packet.ChargePrechargerClosed ?? false,
        ChargePrechargerClosing: packet.ChargePrechargerClosing ?? false,
        ChargePrechargerError: packet.ChargePrechargerError ?? false,
        CommonChargeCurrent: packet.CommonChargeCurrent ?? 0,
        CommonContactorClosed: packet.CommonContactorClosed ?? false,
        CommonContactorClosing: packet.CommonContactorClosing ?? false,
        CommonContactorError: packet.CommonContactorError ?? false,
        CommonContactorOpeningError: packet.CommonContactorOpeningError ?? false,
        CommonHeartbeat: packet.CommonHeartbeat ?? false,
        CommonLineCurrent: packet.CommonLineCurrent ?? 0,
        CommonPrechargerClosed: packet.CommonPrechargerClosed ?? false,
        CommonPrechargerClosing: packet.CommonPrechargerClosing ?? false,
        CommonPrechargerError: packet.CommonPrechargerError ?? false,
        LvBpsError: packet.LvBpsError ?? false,
        LvChargeCurrent: packet.LvChargeCurrent ?? 0,
        LvContactorClosed: packet.LvContactorClosed ?? false,
        LvContactorClosing: packet.LvContactorClosing ?? false,
        LvContactorError: packet.LvContactorError ?? false,
        LvHeartbeat: packet.LvHeartbeat ?? false,
        LvLineCurrent: packet.LvLineCurrent ?? 0,
        LvPrechargerClosed: packet.LvPrechargerClosed ?? false,
        LvPrechargerClosing: packet.LvPrechargerClosing ?? false,
        LvPrechargerError: packet.LvPrechargerError ?? false,
        MotorBPSError: packet.MotorBPSError ?? false,
        MotorChargeCurrent: packet.MotorChargeCurrent ?? 0,
        MotorContactorClosed: packet.MotorContactorClosed ?? false,
        MotorContactorClosing: packet.MotorContactorClosing ?? false,
        MotorContactorError: packet.MotorContactorError ?? false,
        MotorHeartbeat: packet.MotorHeartbeat ?? false,
        MotorLineCurrent: packet.MotorLineCurrent ?? 0,
        MotorPrechargerClosed: packet.MotorPrechargerClosed ?? false,
        MotorPrechargerClosing: packet.MotorPrechargerClosing ?? false,
        MotorPrechargerError: packet.MotorPrechargerError ?? false,
      },
      KeyMotor: {
        BusCurrentOut: packet.BusCurrentOut ?? 0,
        KeyMotorVelocity: packet.KeyMotorVelocity ?? 0,
        MotorCurrent: packet.MotorCurrent ?? 0,
      },
      MBMS: {
        AbattDisable: packet.AbattDisable ?? false,
        ArrayContactorCommand: packet.ArrayContactorCommand ?? false,
        ArrayHeartbeatDeadTrip: packet.ArrayHeartbeatDeadTrip ?? false,
        ArrayHighCurrentTrip: packet.ArrayHighCurrentTrip ?? false,
        ArrayHighCurrentWarning: packet.ArrayHighCurrentWarning ?? false,
        AuxiliaryBatteryVoltage: packet.AuxiliaryBatteryVoltage ?? 0,
        CanOc12VWarning: packet.CanOc12VWarning ?? false,
        ChargeContactorCommand: packet.ChargeContactorCommand ?? false,
        ChargeEnable: packet.ChargeEnable ?? false,
        ChargeHeartbeatDeadTrip: packet.ChargeHeartbeatDeadTrip ?? false,
        ChargeHighCurrentTrip: packet.ChargeHighCurrentTrip ?? false,
        ChargeHighCurrentWarning: packet.ChargeHighCurrentWarning ?? false,
        ChargeSafety: packet.ChargeSafety ?? false,
        ChargeShouldTrip: packet.ChargeShouldTrip ?? false,
        ChgFault: packet.ChgFault ?? false,
        ChgLvEn: packet.ChgLvEn ?? false,
        ChgOn: packet.ChgOn ?? false,
        CommonContactorCommand: packet.CommonContactorCommand ?? false,
        CommonHeartbeatDeadTrip: packet.CommonHeartbeatDeadTrip ?? false,
        CommonHighCurrentTrip: packet.CommonHighCurrentTrip ?? false,
        CommonHighCurrentWarning: packet.CommonHighCurrentWarning ?? false,
        ContactorConnectedUnexpectedlyTrip: packet.ContactorConnectedUnexpectedlyTrip ?? false,
        ContactorDisconnectedUnexpectedlyTrip: packet.ContactorDisconnectedUnexpectedlyTrip ?? false,
        DcdcFault: packet.DcdcFault ?? false,
        DcdcOn: packet.DcdcOn ?? false,
        DischargeEnable: packet.DischargeEnable ?? false,
        DischargeShouldTrip: packet.DischargeShouldTrip ?? false,
        En1: packet.En1 ?? false,
        EsdEnabledTrip: packet.EsdEnabledTrip ?? false,
        ExternalShutdown: packet.ExternalShutdown ?? false,
        Heartbeat: packet.Heartbeat ?? false,
        HighCellVoltageTrip: packet.HighCellVoltageTrip ?? false,
        HighCellVoltageWarning: packet.HighCellVoltageWarning ?? false,
        HighTemperatureTrip: packet.HighTemperatureTrip ?? false,
        HighTemperatureWarning: packet.HighTemperatureWarning ?? false,
        Key: packet.Key ?? false,
        LowCellVoltageTrip: packet.LowCellVoltageTrip ?? false,
        LowCellVoltageWarning: packet.LowCellVoltageWarning ?? false,
        LowTemperatureTrip: packet.LowTemperatureTrip ?? false,
        LowTemperatureWarning: packet.LowTemperatureWarning ?? false,
        LvContactorCommand: packet.LvContactorCommand ?? false,
        LvHeartbeatDeadTrip: packet.LvHeartbeatDeadTrip ?? false,
        LvHighCurrentTrip: packet.LvHighCurrentTrip ?? false,
        LvHighCurrentWarning: packet.LvHighCurrentWarning ?? false,
        MainPowerSwitch: packet.MainPowerSwitch ?? false,
        MotorContactorCommand: packet.MotorContactorCommand ?? false,
        MotorHeartbeatDeadTrip: packet.MotorHeartbeatDeadTrip ?? false,
        MotorHighCurrentTrip: packet.MotorHighCurrentTrip ?? false,
        MotorHighCurrentWarning: packet.MotorHighCurrentWarning ?? false,
        MpsDisabledTrip: packet.MpsDisabledTrip ?? false,
        OrionCanReceivedRecently: packet.OrionCanReceivedRecently ?? false,
        OrionMessageTimeoutTrip: packet.OrionMessageTimeoutTrip ?? false,
        ProtectionTrip: packet.ProtectionTrip ?? false,
        StartupState: packet.StartupState ?? 0,
        StrobeBmsLight: packet.StrobeBmsLight ?? false,
        SystemState: packet.SystemState ?? 0,
        ThreeAOc: packet.ThreeAOc ?? false,
      },
      MotorDetails0: {
        ActiveMotor: packet.Motor0ActiveMotor ?? 0,
        BEMF_D: packet.Motor0BemfD ?? 0,
        BEMF_Q: packet.Motor0BemfQ ?? 0,
        BusCurrent: packet.Motor0BusCurrent ?? 0,
        BusVoltage: packet.Motor0BusVoltage ?? 0,
        DC_Bus_Ah: packet.Motor0DcBusAh ?? 0,
        DspBoardTemperature: packet.Motor0DspBoardTemperature ?? 0,
        ErrorFlags: packet.Motor0ErrorFlags ?? 0,
        HeatsinkTemperature: packet.Motor0HeatsinkTemperature ?? 0,
        Id: packet.Motor0Id ?? 0,
        Iq: packet.Motor0Iq ?? 0,
        LimitFlags: packet.Motor0LimitFlags ?? 0,
        MotorId: 0,
        MotorTemperature: packet.Motor0MotorTemperature ?? 0,
        MotorVelocity: packet.Motor0MotorVelocity ?? 0,
        Odometer: packet.Motor0Odometer ?? 0,
        PhaseCurrentB: packet.Motor0PhaseCurrentB ?? 0,
        PhaseCurrentC: packet.Motor0PhaseCurrentC ?? 0,
        RxErrorCount: packet.Motor0RxErrorCount ?? 0,
        SerialNumber: packet.Motor0SerialNumber ?? 0,
        SlipSpeed: packet.Motor0SlipSpeed ?? 0,
        Supply15V: packet.Motor0Supply15v ?? 0,
        Supply1V9: packet.Motor0Supply1v9 ?? 0,
        Supply3V3: packet.Motor0Supply3v3 ?? 0,
        TritiumId: packet.Motor0TritiumId ?? 0,
        TxErrorCount: packet.Motor0TxErrorCount ?? 0,
        Vd: packet.Motor0Vd ?? 0,
        VehicleVelocity: packet.Motor0VehicleVelocity ?? 0,
        Vq: packet.Motor0Vq ?? 0,
      },
      MotorDetails1: {
        ActiveMotor: packet.Motor1ActiveMotor ?? 0,
        BEMF_D: packet.Motor1BemfD ?? 0,
        BEMF_Q: packet.Motor1BemfQ ?? 0,
        BusCurrent: packet.Motor1BusCurrent ?? 0,
        BusVoltage: packet.Motor1BusVoltage ?? 0,
        DC_Bus_Ah: packet.Motor1DcBusAh ?? 0,
        DspBoardTemperature: packet.Motor1DspBoardTemperature ?? 0,
        ErrorFlags: packet.Motor1ErrorFlags ?? 0,
        HeatsinkTemperature: packet.Motor1HeatsinkTemperature ?? 0,
        Id: packet.Motor1Id ?? 0,
        Iq: packet.Motor1Iq ?? 0,
        LimitFlags: packet.Motor1LimitFlags ?? 0,
        MotorId: 1,
        MotorTemperature: packet.Motor1MotorTemperature ?? 0,
        MotorVelocity: packet.Motor1MotorVelocity ?? 0,
        Odometer: packet.Motor1Odometer ?? 0,
        PhaseCurrentB: packet.Motor1PhaseCurrentB ?? 0,
        PhaseCurrentC: packet.Motor1PhaseCurrentC ?? 0,
        RxErrorCount: packet.Motor1RxErrorCount ?? 0,
        SerialNumber: packet.Motor1SerialNumber ?? 0,
        SlipSpeed: packet.Motor1SlipSpeed ?? 0,
        Supply15V: packet.Motor1Supply15v ?? 0,
        Supply1V9: packet.Motor1Supply1v9 ?? 0,
        Supply3V3: packet.Motor1Supply3v3 ?? 0,
        TritiumId: packet.Motor1TritiumId ?? 0,
        TxErrorCount: packet.Motor1TxErrorCount ?? 0,
        Vd: packet.Motor1Vd ?? 0,
        VehicleVelocity: packet.Motor1VehicleVelocity ?? 0,
        Vq: packet.Motor1Vq ?? 0,
      },
      MPPT: {
        Mppt0Ch0ArrayCurrent: packet.Mppt0Ch0ArrayCurrent ?? 0,
        Mppt0Ch0ArrayVoltage: packet.Mppt0Ch0ArrayVoltage ?? 0,
        Mppt0Ch0BatteryVoltage: packet.Mppt0Ch0BatteryVoltage ?? 0,
        Mppt0Ch0UnitTemperature: packet.Mppt0Ch0UnitTemperature ?? 0,
        Mppt0Ch1ArrayCurrent: packet.Mppt0Ch1ArrayCurrent ?? 0,
        Mppt0Ch1ArrayVoltage: packet.Mppt0Ch1ArrayVoltage ?? 0,
        Mppt0Ch1BatteryVoltage: packet.Mppt0Ch1BatteryVoltage ?? 0,
        Mppt0Ch1UnitTemperature: packet.Mppt0Ch1UnitTemperature ?? 0,
        Mppt1Ch0ArrayCurrent: packet.Mppt1Ch0ArrayCurrent ?? 0,
        Mppt1Ch0ArrayVoltage: packet.Mppt1Ch0ArrayVoltage ?? 0,
        Mppt1Ch0BatteryVoltage: packet.Mppt1Ch0BatteryVoltage ?? 0,
        Mppt1Ch0UnitTemperature: packet.Mppt1Ch0UnitTemperature ?? 0,
        Mppt1Ch1ArrayCurrent: packet.Mppt1Ch1ArrayCurrent ?? 0,
        Mppt1Ch1ArrayVoltage: packet.Mppt1Ch1ArrayVoltage ?? 0,
        Mppt1Ch1BatteryVoltage: packet.Mppt1Ch1BatteryVoltage ?? 0,
        Mppt1Ch1UnitTemperature: packet.Mppt1Ch1UnitTemperature ?? 0,
        Mppt2Ch0ArrayCurrent: packet.Mppt2Ch0ArrayCurrent ?? 0,
        Mppt2Ch0ArrayVoltage: packet.Mppt2Ch0ArrayVoltage ?? 0,
        Mppt2Ch0BatteryVoltage: packet.Mppt2Ch0BatteryVoltage ?? 0,
        Mppt2Ch0UnitTemperature: packet.Mppt2Ch0UnitTemperature ?? 0,
        Mppt2Ch1ArrayCurrent: packet.Mppt2Ch1ArrayCurrent ?? 0,
        Mppt2Ch1ArrayVoltage: packet.Mppt2Ch1ArrayVoltage ?? 0,
        Mppt2Ch1BatteryVoltage: packet.Mppt2Ch1BatteryVoltage ?? 0,
        Mppt2Ch1UnitTemperature: packet.Mppt2Ch1UnitTemperature ?? 0,
        Mppt3Ch0ArrayCurrent: packet.Mppt3Ch0ArrayCurrent ?? 0,
        Mppt3Ch0ArrayVoltage: packet.Mppt3Ch0ArrayVoltage ?? 0,
        Mppt3Ch0BatteryVoltage: packet.Mppt3Ch0BatteryVoltage ?? 0,
        Mppt3Ch0UnitTemperature: packet.Mppt3Ch0UnitTemperature ?? 0,
        Mppt3Ch1ArrayCurrent: packet.Mppt3Ch1ArrayCurrent ?? 0,
        Mppt3Ch1ArrayVoltage: packet.Mppt3Ch1ArrayVoltage ?? 0,
        Mppt3Ch1BatteryVoltage: packet.Mppt3Ch1BatteryVoltage ?? 0,
        Mppt3Ch1UnitTemperature: packet.Mppt3Ch1UnitTemperature ?? 0,
      },
      Pi: {
        Rfid: packet.rfid,
      },
      ProximitySensors: {
        ProximitySensor1: packet.ProximitySensor1 ?? 0,
        ProximitySensor2: packet.ProximitySensor2 ?? 0,
        ProximitySensor3: packet.ProximitySensor3 ?? 0,
        ProximitySensor4: packet.ProximitySensor4 ?? 0,
      },
      Telemetry: {
        GpsAdditionalFlags: packet.GpsAdditionalFlags ?? 0,
        GpsDay: packet.GpsDay ?? 0,
        GpsFixStatusFlags: packet.GpsFixStatusFlags ?? 0,
        GpsHour: packet.GpsHour ?? 0,
        GpsLatitude: packet.GpsLatitude ?? 0,
        GpsLongitude: packet.GpsLongitude ?? 0,
        GpsMinute: packet.GpsMinute ?? 0,
        GpsMonth: packet.GpsMonth ?? 0,
        GpsSecond: packet.GpsSecond ?? 0,
        GpsValidityFlags: packet.GpsValidityFlags ?? 0,
        GpsYear: packet.GpsYear ?? 0,
        MpuAccelerationX: packet.MpuAccelerationX ?? 0,
        MpuAccelerationY: packet.MpuAccelerationY ?? 0,
        MpuAccelerationZ: packet.MpuAccelerationZ ?? 0,
        MpuRotationX: packet.MpuRotationX ?? 0,
        MpuRotationY: packet.MpuRotationY ?? 0,
        MpuRotationZ: packet.MpuRotationZ ?? 0,
        MpuTemperature: packet.MpuTemperature ?? 0,
      },
      TimeStamp: packet.timestamp.getTime() / 1000,
      Title: packet.Title ?? packet.RaceName ?? "",
    } as ITelemetryData;
  }
}
