-- CreateTable
CREATE TABLE "driver" (
    "rfid" TEXT NOT NULL,
    "Name" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "PK_5ec5aa7279436b862c308d63f5b" PRIMARY KEY ("rfid")
);

-- CreateTable
CREATE TABLE "lap" (
    "Id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "timestamp" TIMESTAMPTZ(6) NOT NULL,
    "rfid" TEXT NOT NULL,
    "LapTime" DOUBLE PRECISION NOT NULL,
    "TotalPowerIn" DOUBLE PRECISION NOT NULL,
    "TotalPowerOut" DOUBLE PRECISION NOT NULL,
    "NetPowerOut" DOUBLE PRECISION NOT NULL,
    "Distance" DOUBLE PRECISION NOT NULL,
    "EnergyConsumed" DOUBLE PRECISION NOT NULL,
    "AmpHours" DOUBLE PRECISION NOT NULL,
    "AveragePackCurrent" DOUBLE PRECISION NOT NULL,
    "BatterySecondsRemaining" DOUBLE PRECISION NOT NULL,
    "AverageSpeed" DOUBLE PRECISION NOT NULL,
    "AverageMotorWattage" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "PK_bde83ce36fb9632ffd544022604" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "telemetry_packet" (
    "timestamp" TIMESTAMPTZ(6) NOT NULL,
    "rfid" TEXT NOT NULL,
    "RaceName" TEXT,
    "Title" TEXT,
    "Acceleration" DOUBLE PRECISION,
    "B3Heartbeat" BOOLEAN,
    "BrakeLightSignalStatus" BOOLEAN,
    "BrakeSwitchDigital" BOOLEAN,
    "DaytimeRunningLightSignalStatus" BOOLEAN,
    "ForwardDigital" BOOLEAN,
    "HandbrakeSwitchDigital" BOOLEAN,
    "HazardLightsInput" BOOLEAN,
    "HeadlightsSwitchInput" BOOLEAN,
    "HeadlightSignalStatus" BOOLEAN,
    "HornSignalStatus" BOOLEAN,
    "HornSwitchDigital" BOOLEAN,
    "LapDigital" BOOLEAN,
    "LeftSignalInput" BOOLEAN,
    "LeftSignalStatus" BOOLEAN,
    "MotorResetDigital" BOOLEAN,
    "NeutralDigital" BOOLEAN,
    "RaceModeDigital" BOOLEAN,
    "RegenBraking" DOUBLE PRECISION,
    "ReverseDigital" BOOLEAN,
    "RightSignalInput" BOOLEAN,
    "RightSignalStatus" BOOLEAN,
    "AlwaysOnSignalStatus" BOOLEAN,
    "AverageCellVoltage" DOUBLE PRECISION,
    "AverageTemperature" DOUBLE PRECISION,
    "BmuAlive" INTEGER,
    "ChargeRelayEnabled" BOOLEAN,
    "ChargerSafetyEnabled" BOOLEAN,
    "DischargeRelayEnabled" BOOLEAN,
    "FanSpeed" DOUBLE PRECISION,
    "FanVoltage" DOUBLE PRECISION,
    "HighCellVoltage" DOUBLE PRECISION,
    "HighCellVoltageId" INTEGER,
    "HighTemperature" DOUBLE PRECISION,
    "HighThermistorId" INTEGER,
    "InternalTemperature" DOUBLE PRECISION,
    "IsChargingSignalStatus" BOOLEAN,
    "IsReadySignalStatus" BOOLEAN,
    "LowCellVoltage" DOUBLE PRECISION,
    "LowCellVoltageId" INTEGER,
    "LowTemperature" DOUBLE PRECISION,
    "LowThermistorId" INTEGER,
    "MalfunctionIndicatorActive" BOOLEAN,
    "MaximumCellVoltage" DOUBLE PRECISION,
    "MaximumPackVoltage" DOUBLE PRECISION,
    "MinimumCellVoltage" DOUBLE PRECISION,
    "MinimumPackVoltage" DOUBLE PRECISION,
    "MultiPurposeInputSignalStatus" BOOLEAN,
    "PackAmphours" DOUBLE PRECISION,
    "PackCurrent" DOUBLE PRECISION,
    "PackDepthOfDischarge" DOUBLE PRECISION,
    "PackStateOfCharge" DOUBLE PRECISION,
    "PackVoltage" DOUBLE PRECISION,
    "PopulatedCells" INTEGER,
    "RequestedFanSpeed" DOUBLE PRECISION,
    "ArrayChargeCurrent" DOUBLE PRECISION,
    "ArrayContactorClosed" BOOLEAN,
    "ArrayContactorClosing" BOOLEAN,
    "ArrayContactorError" BOOLEAN,
    "ArrayHeartbeat" BOOLEAN,
    "ArrayLineCurrent" DOUBLE PRECISION,
    "ArrayPrechargerClosed" BOOLEAN,
    "ArrayPrechargerClosing" BOOLEAN,
    "ArrayPrechargerError" BOOLEAN,
    "ChargeChargeCurrent" DOUBLE PRECISION,
    "ChargeContactorClosed" BOOLEAN,
    "ChargeContactorClosing" BOOLEAN,
    "ChargeContactorError" BOOLEAN,
    "ChargeHeartbeat" BOOLEAN,
    "ChargeLineCurrent" DOUBLE PRECISION,
    "ChargePrechargerClosed" BOOLEAN,
    "ChargePrechargerClosing" BOOLEAN,
    "ChargePrechargerError" BOOLEAN,
    "CommonChargeCurrent" DOUBLE PRECISION,
    "CommonContactorClosed" BOOLEAN,
    "CommonContactorClosing" BOOLEAN,
    "CommonContactorError" BOOLEAN,
    "CommonContactorOpeningError" BOOLEAN,
    "CommonHeartbeat" BOOLEAN,
    "CommonLineCurrent" DOUBLE PRECISION,
    "CommonPrechargerClosed" BOOLEAN,
    "CommonPrechargerClosing" BOOLEAN,
    "CommonPrechargerError" BOOLEAN,
    "LvBpsError" BOOLEAN,
    "LvChargeCurrent" DOUBLE PRECISION,
    "LvContactorClosed" BOOLEAN,
    "LvContactorClosing" BOOLEAN,
    "LvContactorError" BOOLEAN,
    "LvHeartbeat" BOOLEAN,
    "LvLineCurrent" DOUBLE PRECISION,
    "LvPrechargerClosed" BOOLEAN,
    "LvPrechargerClosing" BOOLEAN,
    "LvPrechargerError" BOOLEAN,
    "MotorChargeCurrent" DOUBLE PRECISION,
    "MotorContactorClosed" BOOLEAN,
    "MotorContactorClosing" BOOLEAN,
    "MotorContactorError" BOOLEAN,
    "MotorHeartbeat" BOOLEAN,
    "MotorLineCurrent" DOUBLE PRECISION,
    "MotorPrechargerClosed" BOOLEAN,
    "MotorPrechargerClosing" BOOLEAN,
    "MotorPrechargerError" BOOLEAN,
    "BusCurrentOut" DOUBLE PRECISION,
    "KeyMotorVelocity" DOUBLE PRECISION,
    "MotorCurrent" DOUBLE PRECISION,
    "AbattDisable" BOOLEAN,
    "ArrayContactorCommand" BOOLEAN,
    "ArrayHeartbeatDeadTrip" BOOLEAN,
    "ArrayHighCurrentTrip" BOOLEAN,
    "ArrayHighCurrentWarning" BOOLEAN,
    "AuxiliaryBatteryVoltage" DOUBLE PRECISION,
    "ChargeContactorCommand" BOOLEAN,
    "ChargeEnable" BOOLEAN,
    "ChargeHeartbeatDeadTrip" BOOLEAN,
    "ChargeHighCurrentTrip" BOOLEAN,
    "ChargeHighCurrentWarning" BOOLEAN,
    "ChargeSafety" BOOLEAN,
    "ChargeShouldTrip" BOOLEAN,
    "ChgFault" BOOLEAN,
    "ChgLvEn" BOOLEAN,
    "ChgOn" BOOLEAN,
    "CommonContactorCommand" BOOLEAN,
    "CommonHeartbeatDeadTrip" BOOLEAN,
    "CommonHighCurrentTrip" BOOLEAN,
    "CommonHighCurrentWarning" BOOLEAN,
    "ContactorConnectedUnexpectedlyTrip" BOOLEAN,
    "ContactorDisconnectedUnexpectedlyTrip" BOOLEAN,
    "DcdcFault" BOOLEAN,
    "DcdcOn" BOOLEAN,
    "DischargeEnable" BOOLEAN,
    "DischargeShouldTrip" BOOLEAN,
    "En1" BOOLEAN,
    "EsdEnabledTrip" BOOLEAN,
    "ExternalShutdown" BOOLEAN,
    "Heartbeat" BOOLEAN,
    "HighCellVoltageTrip" BOOLEAN,
    "HighCellVoltageWarning" BOOLEAN,
    "HighTemperatureTrip" BOOLEAN,
    "HighTemperatureWarning" BOOLEAN,
    "Key" BOOLEAN,
    "LowCellVoltageTrip" BOOLEAN,
    "LowCellVoltageWarning" BOOLEAN,
    "LowTemperatureTrip" BOOLEAN,
    "LowTemperatureWarning" BOOLEAN,
    "LvContactorCommand" BOOLEAN,
    "LvHeartbeatDeadTrip" BOOLEAN,
    "LvHighCurrentTrip" BOOLEAN,
    "LvHighCurrentWarning" BOOLEAN,
    "MainPowerSwitch" BOOLEAN,
    "MotorContactorCommand" BOOLEAN,
    "MotorHeartbeatDeadTrip" BOOLEAN,
    "MotorHighCurrentTrip" BOOLEAN,
    "MotorHighCurrentWarning" BOOLEAN,
    "MpsDisabledTrip" BOOLEAN,
    "OrionCanReceivedRecently" BOOLEAN,
    "OrionMessageTimeoutTrip" BOOLEAN,
    "ProtectionTrip" BOOLEAN,
    "StartupState" DOUBLE PRECISION,
    "StrobeBmsLight" BOOLEAN,
    "SystemState" DOUBLE PRECISION,
    "ThreeAOc" BOOLEAN,
    "Motor0ActiveMotor" DOUBLE PRECISION,
    "Motor0BemfD" DOUBLE PRECISION,
    "Motor0BemfQ" DOUBLE PRECISION,
    "Motor0BusCurrent" DOUBLE PRECISION,
    "Motor0BusVoltage" DOUBLE PRECISION,
    "Motor0DcBusAh" DOUBLE PRECISION,
    "Motor0DspBoardTemperature" DOUBLE PRECISION,
    "Motor0ErrorFlags" DOUBLE PRECISION,
    "Motor0HeatsinkTemperature" DOUBLE PRECISION,
    "Motor0Id" DOUBLE PRECISION,
    "Motor0Iq" DOUBLE PRECISION,
    "Motor0LimitFlags" DOUBLE PRECISION,
    "Motor0MotorTemperature" DOUBLE PRECISION,
    "Motor0MotorVelocity" DOUBLE PRECISION,
    "Motor0Odometer" DOUBLE PRECISION,
    "Motor0PhaseCurrentB" DOUBLE PRECISION,
    "Motor0PhaseCurrentC" DOUBLE PRECISION,
    "Motor0RxErrorCount" DOUBLE PRECISION,
    "Motor0SerialNumber" DOUBLE PRECISION,
    "Motor0SlipSpeed" DOUBLE PRECISION,
    "Motor0Supply15v" DOUBLE PRECISION,
    "Motor0Supply1v9" DOUBLE PRECISION,
    "Motor0Supply3v3" DOUBLE PRECISION,
    "Motor0TritiumId" DOUBLE PRECISION,
    "Motor0TxErrorCount" DOUBLE PRECISION,
    "Motor0Vd" DOUBLE PRECISION,
    "Motor0VehicleVelocity" DOUBLE PRECISION,
    "Motor0Vq" DOUBLE PRECISION,
    "Motor1ActiveMotor" DOUBLE PRECISION,
    "Motor1BemfD" DOUBLE PRECISION,
    "Motor1BemfQ" DOUBLE PRECISION,
    "Motor1BusCurrent" DOUBLE PRECISION,
    "Motor1BusVoltage" DOUBLE PRECISION,
    "Motor1DcBusAh" DOUBLE PRECISION,
    "Motor1DspBoardTemperature" DOUBLE PRECISION,
    "Motor1ErrorFlags" DOUBLE PRECISION,
    "Motor1HeatsinkTemperature" DOUBLE PRECISION,
    "Motor1Id" DOUBLE PRECISION,
    "Motor1Iq" DOUBLE PRECISION,
    "Motor1LimitFlags" DOUBLE PRECISION,
    "Motor1MotorTemperature" DOUBLE PRECISION,
    "Motor1MotorVelocity" DOUBLE PRECISION,
    "Motor1Odometer" DOUBLE PRECISION,
    "Motor1PhaseCurrentB" DOUBLE PRECISION,
    "Motor1PhaseCurrentC" DOUBLE PRECISION,
    "Motor1RxErrorCount" DOUBLE PRECISION,
    "Motor1SerialNumber" DOUBLE PRECISION,
    "Motor1SlipSpeed" DOUBLE PRECISION,
    "Motor1Supply15v" DOUBLE PRECISION,
    "Motor1Supply1v9" DOUBLE PRECISION,
    "Motor1Supply3v3" DOUBLE PRECISION,
    "Motor1TritiumId" DOUBLE PRECISION,
    "Motor1TxErrorCount" DOUBLE PRECISION,
    "Motor1Vd" DOUBLE PRECISION,
    "Motor1VehicleVelocity" DOUBLE PRECISION,
    "Motor1Vq" DOUBLE PRECISION,
    "Mppt0Ch0ArrayCurrent" DOUBLE PRECISION,
    "Mppt0Ch0ArrayVoltage" DOUBLE PRECISION,
    "Mppt0Ch0BatteryVoltage" DOUBLE PRECISION,
    "Mppt0Ch0UnitTemperature" DOUBLE PRECISION,
    "Mppt0Ch1ArrayCurrent" DOUBLE PRECISION,
    "Mppt0Ch1ArrayVoltage" DOUBLE PRECISION,
    "Mppt0Ch1BatteryVoltage" DOUBLE PRECISION,
    "Mppt0Ch1UnitTemperature" DOUBLE PRECISION,
    "Mppt1Ch0ArrayCurrent" DOUBLE PRECISION,
    "Mppt1Ch0ArrayVoltage" DOUBLE PRECISION,
    "Mppt1Ch0BatteryVoltage" DOUBLE PRECISION,
    "Mppt1Ch0UnitTemperature" DOUBLE PRECISION,
    "Mppt1Ch1ArrayCurrent" DOUBLE PRECISION,
    "Mppt1Ch1ArrayVoltage" DOUBLE PRECISION,
    "Mppt1Ch1BatteryVoltage" DOUBLE PRECISION,
    "Mppt1Ch1UnitTemperature" DOUBLE PRECISION,
    "Mppt2Ch0ArrayCurrent" DOUBLE PRECISION,
    "Mppt2Ch0ArrayVoltage" DOUBLE PRECISION,
    "Mppt2Ch0BatteryVoltage" DOUBLE PRECISION,
    "Mppt2Ch0UnitTemperature" DOUBLE PRECISION,
    "Mppt2Ch1ArrayCurrent" DOUBLE PRECISION,
    "Mppt2Ch1ArrayVoltage" DOUBLE PRECISION,
    "Mppt2Ch1BatteryVoltage" DOUBLE PRECISION,
    "Mppt2Ch1UnitTemperature" DOUBLE PRECISION,
    "Mppt3Ch0ArrayCurrent" DOUBLE PRECISION,
    "Mppt3Ch0ArrayVoltage" DOUBLE PRECISION,
    "Mppt3Ch0BatteryVoltage" DOUBLE PRECISION,
    "Mppt3Ch0UnitTemperature" DOUBLE PRECISION,
    "Mppt3Ch1ArrayCurrent" DOUBLE PRECISION,
    "Mppt3Ch1ArrayVoltage" DOUBLE PRECISION,
    "Mppt3Ch1BatteryVoltage" DOUBLE PRECISION,
    "Mppt3Ch1UnitTemperature" DOUBLE PRECISION,
    "ProximitySensor1" DOUBLE PRECISION,
    "ProximitySensor2" DOUBLE PRECISION,
    "ProximitySensor3" DOUBLE PRECISION,
    "ProximitySensor4" DOUBLE PRECISION,
    "GpsAdditionalFlags" DOUBLE PRECISION,
    "GpsDay" DOUBLE PRECISION,
    "GpsFixStatusFlags" DOUBLE PRECISION,
    "GpsHour" DOUBLE PRECISION,
    "GpsLatitude" DOUBLE PRECISION,
    "GpsLongitude" DOUBLE PRECISION,
    "GpsMinute" DOUBLE PRECISION,
    "GpsMonth" DOUBLE PRECISION,
    "GpsSecond" DOUBLE PRECISION,
    "GpsValidityFlags" DOUBLE PRECISION,
    "GpsYear" DOUBLE PRECISION,
    "MpuAccelerationX" DOUBLE PRECISION,
    "MpuAccelerationY" DOUBLE PRECISION,
    "MpuAccelerationZ" DOUBLE PRECISION,
    "MpuRotationX" DOUBLE PRECISION,
    "MpuRotationY" DOUBLE PRECISION,
    "MpuRotationZ" DOUBLE PRECISION,
    "MpuTemperature" DOUBLE PRECISION,
    "Input12V" DOUBLE PRECISION,
    "AlwaysOnSupplyFault" BOOLEAN,
    "ArrayBPSError" BOOLEAN,
    "CanOc12VWarning" BOOLEAN,
    "CanbusCommunicationFault" BOOLEAN,
    "CclReducedDueToAlternateCurrentLimit" BOOLEAN,
    "CclReducedDueToChargerLatch" BOOLEAN,
    "CclReducedDueToHighCellResistance" BOOLEAN,
    "CclReducedDueToHighCellVoltage" BOOLEAN,
    "CclReducedDueToHighPackVoltage" BOOLEAN,
    "CclReducedDueToHighSoc" BOOLEAN,
    "CclReducedDueToTemperature" BOOLEAN,
    "ChargeBPSError" BOOLEAN,
    "ChargeLimitEnforcementFault" BOOLEAN,
    "ChargerSafetyRelayFault" BOOLEAN,
    "CurrentSensorFault" BOOLEAN,
    "DclAndCclReducedDueToCommunicationFailsafe" BOOLEAN,
    "DclAndCclReducedDueToVoltageFailsafe" BOOLEAN,
    "DclReducedDueToHighCellResistance" BOOLEAN,
    "DclReducedDueToLowCellVoltage" BOOLEAN,
    "DclReducedDueToLowPackVoltage" BOOLEAN,
    "DclReducedDueToLowSoc" BOOLEAN,
    "DclReducedDueToTemperature" BOOLEAN,
    "DischargeLimitEnforcementFault" BOOLEAN,
    "FanMonitorFault" BOOLEAN,
    "HighVoltageIsolationFault" BOOLEAN,
    "InternalCommunicationFault" BOOLEAN,
    "InternalConversionFault" BOOLEAN,
    "InternalLogicFault" BOOLEAN,
    "InternalMemoryFault" BOOLEAN,
    "InternalThermistorFault" BOOLEAN,
    "LowCellVoltageFault" BOOLEAN,
    "MotorBPSError" BOOLEAN,
    "OpenWiringFault" BOOLEAN,
    "PackVoltageSensorFault" BOOLEAN,
    "PowerSupply12VFault" BOOLEAN,
    "ThermistorFault" BOOLEAN,
    "VoltageRedundancyFault" BOOLEAN,
    "WeakCellFault" BOOLEAN,
    "WeakPackFault" BOOLEAN,

    CONSTRAINT "PK_9a0efd28da0c9c4ddb0a002345c" PRIMARY KEY ("timestamp","rfid")
);

-- CreateIndex
CREATE INDEX "IDX_847b73ee1f3faf017fe4e9a6cb" ON "lap"("rfid", "timestamp");

-- CreateIndex
CREATE INDEX "IDX_667eee2eb4f507ee0f5f9552a6" ON "telemetry_packet"("RaceName", "timestamp");

-- CreateIndex
CREATE INDEX "IDX_9a0efd28da0c9c4ddb0a002345" ON "telemetry_packet"("rfid", "timestamp");
