version: 0.2

phases:
  install:
    commands:
      - pip3 install -q awscli --upgrade --user
  pre_build:
    commands:
      ### Login to Amazon ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      ### Building the image
      - echo Build started on `date`
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Build completed on `date`
  post_build:
    commands:
      ### Publish the docker image to ECR
      - echo Pushing the Docker image...
      - docker push 602361116849.dkr.ecr.ca-central-1.amazonaws.com/amplify-heliostelemetry-ideen-sandbox-b3c638db35-telemetrybackend00f6569c-1jtacvwuc0nq2-telemetrybackendimagerepository54de1605-xvsgq7iiqx7o:latest
