version: "3.9"

services:
  db:
    image: timescale/timescaledb-ha:pg17 # Image for timescale db with postgres 17
    env_file:
      - .db.env # contains the information regarding our user, password, and database
    ports:
      - "5432:5432" # map host port to internal port
    volumes:
      - /var/lib/timescaledb/data:/home/postgres/pgdata/data # volume to store persistence in case the container spins down/fails etc
    restart: unless-stopped # try to restart it unless manually stopped

