version: "3.9"

services:
  db:
    image: postgres:17 # Plain Postgres image
    env_file:
      - .db.env # contains the information regarding our user, password, and database
    ports:
      - "5432:5432" # map host port to internal port
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data # volume to store persistence in case the container spins down/fails etc
    restart: unless-stopped # try to restart it unless manually stopped
    environment:
      # Disable HA features for local development (we just want the toolkit)
      PATRONI_SCOPE: local-dev

volumes:
  postgres_data: # Named volume for database persistence

