/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 packages/client/public/models/Helios.glb --types --keepnames 
*/
import React from "react";
import type * as THREE from "three";
import { type GLTF } from "three-stdlib";

import {
  ISeverity,
  type IndicationLocations,
} from "@/components/molecules/HeroMolecules/HeroTypes";
import { useGLTF } from "@react-three/drei";

// wheels, solar panels, big battery

type GLTFResult = GLTF & {
  nodes: {
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid2_-_Part"]: THREE.Mesh; // Left window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid3_-_Part"]: THREE.Mesh; // Left windshield
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid3_-_Part_clonedChild"]: THREE.Mesh; // Left windshield2
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part"]: THREE.Mesh; // Left window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part_2"]: THREE.Mesh; // Left window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part_3"]: THREE.Mesh; // Left window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid5_-_Part"]: THREE.Mesh; // Left window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid5_-_Part_2"]: THREE.Mesh; // Left window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid6_-_Part"]: THREE.Mesh; // Left front wheel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid7_-_Part"]: THREE.Mesh; // Left back wheel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid8_-_Part"]: THREE.Mesh; // Left back piece
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid8_-_Part_2"]: THREE.Mesh; // Left back piece2
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid9_-_Part"]: THREE.Mesh; // Top of the car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid9_-_Part_2"]: THREE.Mesh; // Top solar panel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid10_-_Part"]: THREE.Mesh; // Top left solar panel frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid11_-_Part"]: THREE.Mesh; // Top left solar panel frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid12_-_Part"]: THREE.Mesh; // Top left solar panel frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid13_-_Part"]: THREE.Mesh; // Left door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part"]: THREE.Mesh; // Left door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part_2"]: THREE.Mesh; // Left door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part_3"]: THREE.Mesh; // Left door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part"]: THREE.Mesh; // Left door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_2"]: THREE.Mesh; // Left door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_3"]: THREE.Mesh; // Left front solar panel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_4"]: THREE.Mesh; // Weird led thing
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_5"]: THREE.Mesh; // Another weird led thing
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part"]: THREE.Mesh; // Left back frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_2"]: THREE.Mesh; // Left back frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_3"]: THREE.Mesh; // Left back frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_4"]: THREE.Mesh; // Left back solar panel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part"]: THREE.Mesh; // Bottom frame of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_2"]: THREE.Mesh; // Bottom frame of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_3"]: THREE.Mesh; // Bottom frame of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_4"]: THREE.Mesh; // Bottom frame of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid18_-_Part"]: THREE.Mesh; // Top of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid18_-_Part_2"]: THREE.Mesh; // Top solar panel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part"]: THREE.Mesh; // Right back of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_2"]: THREE.Mesh; // Right back of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_3"]: THREE.Mesh; // Right back of car
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_4"]: THREE.Mesh; // Right back solar panel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part"]: THREE.Mesh; // right side window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part_2"]: THREE.Mesh; //right sdie window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part_3"]: THREE.Mesh; //right side window frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_2"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_3"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_4"]: THREE.Mesh; // Right front solar panel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_5"]: THREE.Mesh; //left yellow neon tube thing
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_6"]: THREE.Mesh; //right yellow neon tube thing
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part_2"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part_3"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid23_-_Part"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid24_-_Part"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid24_-_Part_clonedChild"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid25_-_Part"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid25_-_Part_2"]: THREE.Mesh; // right door frame
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid26_-_Part"]: THREE.Mesh; //right front wheel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid27_-_Part"]: THREE.Mesh; //right back wheel
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid28_-_Part"]: THREE.Mesh; // Right window
    ["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid28_-_Part_clonedChild"]: THREE.Mesh; //Right window 2
    ["EVO_QRT_(1)-1-surface1_-_Part"]: THREE.Mesh; //another left seat
    ["EVO_QRT_(1)-1-surface1_-_Part_2"]: THREE.Mesh;
    ["EVO_QRT_(1)-2-surface1_-_Part"]: THREE.Mesh; //left seat
    ["EVO_QRT_(1)-2-surface1_-_Part_2"]: THREE.Mesh;
    ["EVO_QRT_(1)-3-surface1_-_Part"]: THREE.Mesh; //another right seat
    ["EVO_QRT_(1)-3-surface1_-_Part_2"]: THREE.Mesh;
    ["EVO_QRT_(1)-4-surface1_-_Part"]: THREE.Mesh; //right seat
    ["EVO_QRT_(1)-4-surface1_-_Part_2"]: THREE.Mesh; //some frame thing
  };
  materials: {
    ["white medium gloss plastic"]: THREE.MeshStandardMaterial;
    ["glossy rubber"]: THREE.MeshStandardMaterial;
    ["matte rubber"]: THREE.MeshStandardMaterial;
    ["white high gloss plastic"]: THREE.MeshStandardMaterial;
    ["carbon fiber eproxy 2d"]: THREE.MeshStandardMaterial;
    ["amber led"]: THREE.MeshBasicMaterial;
    ["white medium gloss plastic-4"]: THREE.MeshStandardMaterial;
    yellow_neon_tube: THREE.MeshBasicMaterial;
    polycarbonate: THREE.MeshStandardMaterial;
    color: THREE.MeshStandardMaterial;
    ["cotton white 2d"]: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[];
};

type CarModelComponentProps = {
  errorMaterial: THREE.MeshStandardMaterial;
  warningMaterial: THREE.MeshStandardMaterial;
  indications: IndicationLocations;
  isClear: boolean;
};

export function CarModelComponent(props: CarModelComponentProps) {
  const { nodes, materials } = useGLTF("/models/Helios.glb") as GLTFResult;

  const clear = materials.polycarbonate;

  return (
    <group
      {...props}
      dispose={null}
      scale={3}
      rotation={[0, Math.PI, 0]}
      position={[-1.5, 0, 6]}
    >
      <directionalLight
        name="Directional1"
        intensity={0.577}
        // decay={2}
        color="#c8c8c8"
        position={[7.071, 7.071, 0]}
        rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]}
      />
      <directionalLight
        name="Directional2"
        intensity={0.577}
        // decay={2}
        color="#c8c8c8"
        position={[-3.414, 6.125, -7.129]}
        rotation={[-2.432, -0.348, -2.856]}
      />
      <directionalLight
        name="Directional3"
        intensity={0.577}
        // decay={2}
        color="#c8c8c8"
        position={[-9.226, 3.41, -1.805]}
        rotation={[-2.058, -1.175, -2.092]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid2_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid2_-_Part"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid3_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid3_-_Part"].geometry
        }
        material={materials.polycarbonate}
        rotation={[0, Math.PI, 0]}
      >
        <mesh
          name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid3_-_Part_clonedChild"
          geometry={
            nodes[
              "Gen_6_Body_and_Chassis_A6_-_Mold-1-solid3_-_Part_clonedChild"
            ].geometry
          }
          material={materials.polycarbonate}
        />
      </mesh>
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid4_-_Part_3"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid5_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid5_-_Part"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid5_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid5_-_Part_2"].geometry
        }
        material={
          props.indications.solarPanel === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.solarPanel === ISeverity.WARNING
              ? props.warningMaterial
              : materials["glossy rubber"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid6_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid6_-_Part"].geometry
        }
        material={
          props.indications.leftMotor === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.leftMotor === ISeverity.WARNING
              ? props.warningMaterial
              : materials["glossy rubber"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid7_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid7_-_Part"].geometry
        }
        material={
          props.indications.leftMotor === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.leftMotor === ISeverity.WARNING
              ? props.warningMaterial
              : materials["glossy rubber"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid8_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid8_-_Part"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid8_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid8_-_Part_2"].geometry
        }
        material={materials["white high gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid9_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid9_-_Part"].geometry
        }
        material={materials["white medium gloss plastic-4"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid9_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid9_-_Part_2"].geometry
        }
        material={
          props.indications.solarPanel === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.solarPanel === ISeverity.WARNING
              ? props.warningMaterial
              : materials["carbon fiber eproxy 2d"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid10_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid10_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid11_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid11_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid12_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid12_-_Part"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid13_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid13_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid14_-_Part_3"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_2"].geometry
        }
        material={materials["white high gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_3"].geometry
        }
        material={
          props.indications.solarPanel === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.solarPanel === ISeverity.WARNING
              ? props.warningMaterial
              : materials["carbon fiber eproxy 2d"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_4"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_4"].geometry
        }
        material={materials["amber led"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_5"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid15_-_Part_5"].geometry
        }
        material={materials.yellow_neon_tube}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_3"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_4"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid16_-_Part_4"].geometry
        }
        material={
          props.indications.solarPanel === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.solarPanel === ISeverity.WARNING
              ? props.warningMaterial
              : materials["carbon fiber eproxy 2d"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_3"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_4"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid17_-_Part_4"].geometry
        }
        material={materials["white high gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid18_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid18_-_Part"].geometry
        }
        material={materials["white medium gloss plastic-4"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid18_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid18_-_Part_2"].geometry
        }
        material={
          props.indications.solarPanel === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.solarPanel === ISeverity.WARNING
              ? props.warningMaterial
              : materials["carbon fiber eproxy 2d"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_3"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_4"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid19_-_Part_4"].geometry
        }
        material={
          props.indications.solarPanel === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.solarPanel === ISeverity.WARNING
              ? props.warningMaterial
              : materials["carbon fiber eproxy 2d"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid20_-_Part_3"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_3"].geometry
        }
        material={materials["white high gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_4"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_4"].geometry
        }
        material={
          props.indications.solarPanel === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.solarPanel === ISeverity.WARNING
              ? props.warningMaterial
              : materials["carbon fiber eproxy 2d"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_5"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_5"].geometry
        }
        material={materials["amber led"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_6"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid21_-_Part_6"].geometry
        }
        material={materials.yellow_neon_tube}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part_2"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part_3"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid22_-_Part_3"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid23_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid23_-_Part"].geometry
        }
        material={materials["glossy rubber"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid24_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid24_-_Part"].geometry
        }
        material={materials.polycarbonate}
        rotation={[0, Math.PI, 0]}
      >
        <mesh
          name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid24_-_Part_clonedChild"
          geometry={
            nodes[
              "Gen_6_Body_and_Chassis_A6_-_Mold-1-solid24_-_Part_clonedChild"
            ].geometry
          }
          material={materials.polycarbonate}
        />
      </mesh>
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid25_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid25_-_Part"].geometry
        }
        material={materials["white medium gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid25_-_Part_2"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid25_-_Part_2"].geometry
        }
        material={materials["white high gloss plastic"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid26_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid26_-_Part"].geometry
        }
        material={
          props.indications.rightMotor === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.rightMotor === ISeverity.WARNING
              ? props.warningMaterial
              : materials["glossy rubber"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid27_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid27_-_Part"].geometry
        }
        material={
          props.indications.rightMotor === ISeverity.ERROR
            ? props.errorMaterial
            : props.indications.rightMotor === ISeverity.WARNING
              ? props.warningMaterial
              : materials["glossy rubber"]
        }
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid28_-_Part"
        geometry={
          nodes["Gen_6_Body_and_Chassis_A6_-_Mold-1-solid28_-_Part"].geometry
        }
        material={materials.polycarbonate}
        rotation={[0, Math.PI, 0]}
      >
        <mesh
          name="Gen_6_Body_and_Chassis_A6_-_Mold-1-solid28_-_Part_clonedChild"
          geometry={
            nodes[
              "Gen_6_Body_and_Chassis_A6_-_Mold-1-solid28_-_Part_clonedChild"
            ].geometry
          }
          material={materials.polycarbonate}
        />
      </mesh>
      <mesh
        name="EVO_QRT_(1)-1-surface1_-_Part"
        geometry={nodes["EVO_QRT_(1)-1-surface1_-_Part"].geometry}
        material={materials.color}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="EVO_QRT_(1)-1-surface1_-_Part_2"
        geometry={nodes["EVO_QRT_(1)-1-surface1_-_Part_2"].geometry}
        material={materials["cotton white 2d"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="EVO_QRT_(1)-2-surface1_-_Part"
        geometry={nodes["EVO_QRT_(1)-2-surface1_-_Part"].geometry}
        material={materials.color}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="EVO_QRT_(1)-2-surface1_-_Part_2"
        geometry={nodes["EVO_QRT_(1)-2-surface1_-_Part_2"].geometry}
        material={materials["cotton white 2d"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="EVO_QRT_(1)-3-surface1_-_Part"
        geometry={nodes["EVO_QRT_(1)-3-surface1_-_Part"].geometry}
        material={materials.color}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="EVO_QRT_(1)-3-surface1_-_Part_2"
        geometry={nodes["EVO_QRT_(1)-3-surface1_-_Part_2"].geometry}
        material={materials["cotton white 2d"]}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="EVO_QRT_(1)-4-surface1_-_Part"
        geometry={nodes["EVO_QRT_(1)-4-surface1_-_Part"].geometry}
        material={materials.color}
        rotation={[0, Math.PI, 0]}
      />
      <mesh
        name="EVO_QRT_(1)-4-surface1_-_Part_2"
        geometry={nodes["EVO_QRT_(1)-4-surface1_-_Part_2"].geometry}
        material={materials["cotton white 2d"]}
        rotation={[0, Math.PI, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Helios.glb");
