name: add reviewers
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ideen1, haley-lynn, justin-phxm, jjason-nn, IshaHaider, CalebBourb

