name: Front End Deploy

on:
  push:
    branches: [ main,
    features/GithubPagesDeployment ]
  pull_request:
    branches: [ main ]

jobs:
  defaults:
    runs-on: ubuntu-latest
    shell: bash
    working-directory: ./web-app
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy react app to github pages
      run: |
        npm install
        npm run deploy