name: "Amplify Merge"
on:
  push:
    paths:
      - "amplify/**"
      - '.github/workflows/**'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: 'main'
          target_branch: 'amplify_master'
          commit_message_template: '[Automated] Merged main to amplify_master because the amplify folder changed'
